#!/usr/bin/env node
// Write the deterministic trace tables the chapters include, from the same model the page runs.
//
//     node tools/trace.mjs            # chapters/_generated/*-trace-*.md
//     node tools/trace.mjs --check    # fail if a committed table is not what the model computes
//
// One implementation of the model (web/lab/trace.js) serves the page and the build, so the table
// a chapter shows and the trace a reader steps through cannot disagree.

import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { run, table } from "../web/lab/trace.js";
import { programs } from "../web/lab/programs.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED = path.join(ROOT, "chapters", "_generated");

// Every table, with the conditions it was computed under, which the fragment states.
const TABLES = [
  {
    file: "counter-trace-alternate.md",
    program: programs.counter({ threads: 2, iterations: 2 }),
    schedule: "alternate",
    conditions: "Two threads, two plain increments each, one operation from each thread in turn.",
  },
  {
    file: "counter-trace-sequential.md",
    program: programs.counter({ threads: 2, iterations: 2 }),
    schedule: "sequential",
    conditions: "Two threads, two plain increments each, the first thread running to the end before the second starts.",
  },
  {
    file: "counter-trace-atomic.md",
    program: programs.counter({ threads: 2, iterations: 2, operation: "atomic" }),
    schedule: "alternate",
    conditions: "Two threads, two atomic increments each, one operation from each thread in turn.",
  },
  {
    file: "counter-trace-folded.md",
    program: programs.counter({ threads: 2, iterations: 1000, operation: "folded" }),
    schedule: "alternate",
    conditions: "Two threads, a thousand increments each folded into one add, one operation from each thread in turn.",
  },
  {
    file: "counter-trace-split.md",
    program: programs.counter({ threads: 2, iterations: 2, operation: "split" }),
    schedule: "alternate",
    conditions: "Two threads, two increments each as an atomic load and an atomic store, one operation from each thread in turn.",
  },
];

function fragment(t) {
  const m = run(t.program, t.schedule);
  const [name, expected] = Object.entries(t.program.expected)[0];
  const got = m.memory[name];
  const summary = `Expected \`${name}\` = ${expected}; final \`${name}\` = ${got}; lost ${expected - got}.`;
  return (
    "% Generated by tools/trace.mjs from web/lab/trace.js. Do not edit.\n" +
    table(m) + "\n\n" + summary + "\n\n" +
    `*A model of each thread's operations, not the compiled code. ${t.conditions}*\n`
  );
}

const check = process.argv.includes("--check");
let bad = 0;
const made = new Map(TABLES.map((t) => [t.file, fragment(t)]));
for (const [file, text] of made) {
  const target = path.join(GENERATED, file);
  if (check) {
    if (!existsSync(target)) { console.log(`  missing: chapters/_generated/${file} (run \`make traces\`)`); bad++; }
    else if (readFileSync(target, "utf8") !== text) { console.log(`  stale: chapters/_generated/${file} (run \`make traces\`)`); bad++; }
  } else {
    writeFileSync(target, text);
  }
}
if (check) {
  for (const f of readdirSync(GENERATED)) {
    if (f.endsWith(".md") && !made.has(f) && readFileSync(path.join(GENERATED, f), "utf8").startsWith("% Generated by tools/trace.mjs")) {
      console.log(`  orphan: chapters/_generated/${f} (no table asks for it)`); bad++;
    }
  }
  if (!bad) console.log(`  ${made.size} trace tables are what the model computes`);
  process.exit(bad ? 1 : 0);
}
console.log(`  wrote ${made.size} trace tables into chapters/_generated`);
